apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-user
  namespace: cinema
  labels:
    app.kubernetes.io/name: web-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-user
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: web-user
          image: ghcr.io/cine-org/setup-monorepo/web-user:v0.1.0
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_ORIGIN
              value: https://api.cine.io.vn
            - name: API_PREFIX
              value: /api/v1
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
