apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-redis
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: infra-redis
  data:
    - secretKey: password
      remoteRef:
        key: infra-redis
        property: password
