apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-postgres
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: platform-postgres
  data:
    - secretKey: username
      remoteRef:
        key: platform-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: platform-postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-postgres-rw
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: platform-postgres-rw
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: platform-postgres-rw
        property: username
    - secretKey: password
      remoteRef:
        key: platform-postgres-rw
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-postgres-ro
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: platform-postgres-ro
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: platform-postgres-ro
        property: username
    - secretKey: password
      remoteRef:
        key: platform-postgres-ro
        property: password
