apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-redis
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: platform-redis
  data:
    - secretKey: password
      remoteRef:
        key: platform-redis
        property: password
