apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# Each env reads its own GCP project.
patches:
  - target:
      kind: ClusterSecretStore
      name: gcp-secret-manager
    patch: |
      - op: replace
        path: /spec/provider/gcpsm/projectID
        value: cinema-production
