apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.10.0
      helm:
        valueFiles:
          - $values/infra/external-secrets/values.yaml
    - repoURL: https://github.com/cine-org/cinema-ops.git
      targetRevision: main
      path: infra/external-secrets/envs/staging
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: infra

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
