apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/cine-org/cinema/web-user
    newTag: v0.1.0

patches:
  - path: deployment-patch.yaml
