apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-postgres
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: infra-postgres
  data:
    - secretKey: username
      remoteRef:
        key: infra-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: infra-postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-postgres-rw
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: infra-postgres-rw
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: infra-postgres-rw
        property: username
    - secretKey: password
      remoteRef:
        key: infra-postgres-rw
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-postgres-ro
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: infra-postgres-ro
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: infra-postgres-ro
        property: username
    - secretKey: password
      remoteRef:
        key: infra-postgres-ro
        property: password
