apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: "project-8fd393bc-2eb7-43e4-a3a"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-credentials
            key: secret-access-credentials
            namespace: infra
