apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID # set per env in envs/<env>
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-credentials
            key: secret-access-credentials
            namespace: infra
